name: Discord Notification Test

env:
  itchio_channel: windows
  BuildName: UnderRunner X.Y.Z
  ReleaseBody: "Changelog: \n Add: Something"

on: workflow_dispatch

jobs:
  discordMessage:
    name: Discord Notification
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@master
      - name: send custom message with args
        uses: appleboy/discord-action@master
        with:
          webhook_id: ${{ secrets.WEBHOOK_ID }}
          webhook_token: ${{ secrets.WEBHOOK_TOKEN }}
          message: "@here ${{ env.BuildName }} is out on https://undermakersinteractive.itch.io/underrunner \n ${{ env.ReleaseBody }} "
