name: Build project

env:
  itchio_channel: windows
  BuildName: UnderRunner ${{ github.event.release.tag_name }}

on:
  release:
    types: [ published ]

jobs:
  buildForWindows:
    name: Build for Windows
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: false
      - uses: actions/cache@v3
        with:
          path: Library
          key: Library-StandaloneWindows
          restore-keys: Library-
      - uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: StandaloneWindows
          buildName: env.BuildName
      - uses: actions/upload-artifact@v4
        with:
          name: env.BuildName
          path: build/StandaloneWindows
  deploy:
    needs: buildForWindows
    name: Deploy to Itch.io
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: false
      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: env.BuildName
          path: build/StandaloneWindows
      - name: Upload Build to itch.io project
        uses: robpc/itchio-upload-action@v1
        with:
          path: build/StandaloneWindows
          project: ${{ secret.ITCHIO_PROJECT }}
          channel: ${{ env.itchio_channel }}
          version: ${{ github.event.release.tag_name }}
          api-key: ${{ secrets.ITCHIO_API_KEY }}
